import type { Topic } from "@/lib/help/content";

export const jobTopics: Topic[] = [
    {
        slug: "quote-to-invoice",
        group: "job",
        title: "From a quote to an invoice",
        question: "How does a job move through MOTION?",
        answer: "One document changes type as the work moves: a quote becomes a job card, and the job card becomes the invoice — it is never re-typed.",
        screens: ["/dashboard/jobs", "/dashboard/documents", "/dashboard/invoices"],
        blocks: [
            { kind: "p", text: "Most workshop software makes you copy a quote into a job card and the job card into an invoice, and the three drift apart. MOTION carries one document the whole way. What you priced is what the mechanic works from, and what the mechanic worked on is what the customer is billed for." },
            { kind: "h", text: "The stages" },
            { kind: "steps", items: [
                "Quote — a price, before anybody has committed to anything. It holds a number as soon as it is raised.",
                "Booking — a day in the diary. Still a draft; nothing has been done yet.",
                "Job card — the car is in. Mechanics clock on to this, parts come off stock against it, inspections hang off it.",
                "Invoice — the work is finished and priced. Processing it is the moment the money becomes real.",
                "Credit note — where an invoice has to be given back, in part or whole.",
            ] },
            { kind: "h", text: "What processing actually does" },
            { kind: "p", text: "Up to the moment you process, a document is a draft: you can change anything on it and nothing has left the building. Processing is the commitment. It stamps the number, takes the parts off stock, and puts the amount onto what the customer owes." },
            { kind: "note", text: "A processed document can never be edited. That is deliberate — an invoice somebody can quietly change is not evidence of anything. If it is wrong, void it and raise a new one, or credit it." },
            { kind: "h", text: "Why the tax on an old invoice does not change" },
            { kind: "p", text: "Each document keeps the tax name and rate it was raised under, stamped onto it at the time. Changing the workshop's tax setting today has no effect on anything already raised. That is what lets a period spanning a rate change show both rates and still be correct." },
        ],
        related: ["void-or-delete", "why-cant-i-edit"],
    },
    {
        slug: "void-or-delete",
        group: "job",
        title: "Voiding and deleting",
        question: "Why can't I delete this invoice?",
        answer: "Voiding cancels a real document and keeps it; deleting removes one that should never have existed, and only works on a draft or a voided document with nothing attached to it.",
        screens: ["/dashboard/documents", "/dashboard/invoices"],
        blocks: [
            { kind: "p", text: "These look like the same thing and are not. Reaching for the wrong one is how a workshop ends up with a hole in its numbering that nobody can explain to an auditor." },
            { kind: "h", text: "Void — for a real document that went wrong" },
            { kind: "p", text: "The invoice was raised, and it should not stand. Voiding cancels it, reverses the stock it moved, re-opens anything it settled, and keeps the document exactly where it was, at nil value, with the reason on it." },
            { kind: "note", text: "A voided document keeps its number, which is why it is not a gap in the sequence. Nothing was quietly removed, and the audit report can prove it." },
            { kind: "h", text: "Delete — for a document that was never a document" },
            { kind: "p", text: "A booking converted twice, a duplicate somebody made by accident. Voiding one of those leaves it in every list for ever, which is clutter rather than a record. Deleting removes the row — but MOTION writes the whole document into the audit trail first: every line, the totals, the customer, the vehicle, who deleted it and the reason they gave." },
            { kind: "h", text: "When delete is refused, and why" },
            { kind: "p", text: "Only a draft or a voided document can be deleted at all. Beyond that, MOTION refuses anything the books depend on, and says which thing by name:" },
            { kind: "list", items: [
                "a payment against it",
                "stock moved for it",
                "an inspection",
                "a courtesy car",
                "a line on a purchase order",
                "a line on a supplier invoice",
                "an online booking request",
            ] },
            { kind: "p", text: "Deleting one of those would orphan a record that answers for money. Void it instead. Messages and reminders do not block a deletion — they are unhooked and kept, because what was said to a customer is a record in its own right." },
            { kind: "p", text: "Deleting needs the same permission as voiding, because it is the stronger version of the same act." },
        ],
        related: ["quote-to-invoice", "the-gap-report"],
    },
    {
        slug: "why-cant-i-edit",
        group: "job",
        title: "Changing something that is already processed",
        question: "Why can't I edit this invoice?",
        answer: "Processed documents are fixed on purpose; correct them with a credit note or by voiding and raising again.",
        screens: ["/dashboard/documents", "/dashboard/invoices"],
        blocks: [
            { kind: "p", text: "An invoice that can be edited after it has been sent is not evidence of anything — and every audit MOTION is built to survive turns on documents that cannot be quietly changed." },
            { kind: "h", text: "What to do instead" },
            { kind: "table", head: ["What is wrong", "What to do"], rows: [
                ["Priced wrong, nothing paid yet", "Void it and raise a new one"],
                ["Priced wrong, already part-paid", "Raise a credit note for the difference"],
                ["Wrong customer", "Void and re-raise against the right one"],
                ["A typo in the description", "Leave it. A credit note over a spelling mistake is worse than the mistake"],
            ] },
            { kind: "note", text: "Voiding an invoice that has been paid re-opens the payment as unapplied credit on the customer's account. The money does not disappear — it goes back to being money you are holding for them." },
        ],
        related: ["void-or-delete", "unapplied-credit"],
    },
];
