import type { Topic } from "@/lib/help/content";

export const reportTopics: Topic[] = [
    {
        slug: "for-the-auditor",
        group: "reports",
        title: "The six an auditor asks for",
        question: "An auditor is coming — what do I give them?",
        answer: "Reports → For the auditor produces all six as a PDF to file and a CSV to re-add, over whatever period they ask for.",
        screens: ["/dashboard/reports/audit", "/dashboard/reports"],
        blocks: [
            { kind: "p", text: "Pick the period first. Every file then says on it which workshop, which period, when it was produced, by whom, and how many rows it should hold — which is the only thing that catches a file truncated on the way out." },
            { kind: "table", head: ["Report", "What it answers"], rows: [
                ["Number sequence and gaps", "Is any document number unaccounted for"],
                ["Sales register", "Every invoice, cash sale and credit note, tax apart"],
                ["Tax summary", "Output tax against input tax, by the rate actually charged"],
                ["Cash book", "Money in and out, grouped by how it moved"],
                ["Debtors age analysis", "What is owed as at the end of the period"],
                ["Transaction log", "Everything anybody did, with who did it"],
            ] },
            { kind: "note", text: "Taking a file out is itself recorded. The transaction log shows who has been exporting data as well as who has been changing it, which is a question councils ask and most workshop software cannot answer at all." },
        ],
        related: ["the-gap-report", "for-the-owner"],
    },
    {
        slug: "the-gap-report",
        group: "reports",
        title: "Number sequence and gaps",
        question: "What does the gap report mean, and what is \"taken, unused\"?",
        answer: "It lists every number issued in a period and accounts for each one that is missing — a void is not a gap, and a number handed out above the last document on the books is reported separately.",
        screens: ["/dashboard/reports/audit"],
        blocks: [
            { kind: "p", text: "An auditor takes your invoice numbers for a period and checks they run without a break. A workshop that cannot explain a missing number is, for the length of that conversation, a workshop that might have deleted an invoice. This report is the answer, prepared before the question." },
            { kind: "h", text: "The three things it can say about a number" },
            { kind: "table", head: ["Status", "Meaning"], rows: [
                ["On the books", "The document exists. A voided one counts here — it kept its number"],
                ["Accounted for", "Missing, and MOTION knows why: it was deleted, and the audit trail holds what it said"],
                ["Unexplained", "Missing with nothing to explain it. This is the finding"],
            ] },
            { kind: "term", term: "Taken, unused", text: "A number the counter handed out above the last document actually on the books — somebody started a document and never finished it. It is reported apart from the gaps because it is not a missing document." },
            { kind: "h", text: "It warns, it does not block" },
            { kind: "p", text: "An unexplained gap does not stop you closing a period. Blocking would mean a support call every time somebody tidied away a draft, and the record is what an auditor actually wants. The warning sits on the page so you find it before they do." },
        ],
        related: ["void-or-delete", "for-the-auditor"],
    },
    {
        slug: "for-the-owner",
        group: "reports",
        title: "The reports you decide with",
        question: "What made money, and what is standing still?",
        answer: "Reports → For the owner ranks every job by what it made, cuts item sales four ways, and shows what is open, owed and on the shelves.",
        screens: ["/dashboard/reports/business", "/dashboard/reports/margin", "/dashboard/reports"],
        blocks: [
            { kind: "p", text: "These are built to be sorted rather than filed, so take the CSV. The PDF is there for anyone who wants it on paper." },
            { kind: "list", items: [
                "Profit by job — every job ranked, the ones that cost more than they brought in at the bottom.",
                "Item sales — the same sales by product, by group, by supplier, and by parts against labour.",
                "Quote outcomes — how many quotes turned into work, and what the difference is worth.",
                "Mechanic time — hours clocked against hours charged.",
                "Work in progress — jobs opened and not yet invoiced.",
                "Stock valuation, creditors, renewals due, and the customer and vehicle listings.",
            ] },
            { kind: "note", text: "If a job shows 100 % margin, the parts on it have no cost recorded. The report says so at the bottom, and the fix is to put a cost on those products rather than to believe the figure." },
        ],
        related: ["stock-valuation", "for-the-auditor"],
    },
    {
        slug: "stock-valuation",
        group: "reports",
        title: "What the stock is worth",
        question: "How much money is sitting on the shelves?",
        answer: "Valued at what it cost, which is the figure a balance sheet takes — the retail column is what it is priced at, and is not the value of anything until it sells.",
        screens: ["/dashboard/reports/business", "/dashboard/products"],
        blocks: [
            { kind: "p", text: "Cost is each product's current cost, not a weighted average of what each unit cost on the day it arrived. MOTION does not keep per-unit cost layers, and a valuation implying otherwise would be worse than one that says which cost it used." },
            { kind: "p", text: "Labour, sublet and anything marked as a service or as not stock-tracked is left out: it has no shelf to count." },
            { kind: "note", text: "Two figures at the foot are worth reading before the total: how many products are showing a negative quantity, and how many have stock on hand with no cost recorded. Both mean the total is wrong in a way the total cannot show." },
        ],
        related: ["stock-on-hand", "for-the-owner"],
    },
    {
        slug: "the-handoff",
        group: "reports",
        title: "Sending the books to the accounting system",
        question: "How does the nightly journal reach our accounts package?",
        answer: "MOTION writes the day's journal into a folder and the accounting system picks it up — nothing listens, and nothing is exposed.",
        screens: ["/dashboard/reports/handoff", "/dashboard/settings/handoff"],
        blocks: [
            { kind: "p", text: "This is the arrangement a council's network people will agree to: traffic goes out, never in. It is also why the Hand-off screen exists, because a folder full of files looks identical whether the accounting system is importing them nightly or stopped in March." },
            { kind: "h", text: "What the screen tells you" },
            { kind: "list", items: [
                "Days in the last fortnight that were never sent.",
                "Files that went out and were never confirmed by the other end.",
                "Every run, with how many lines went and who sent it.",
            ] },
            { kind: "h", text: "Confirmation from the other end" },
            { kind: "p", text: "When the import succeeds, the accounting system drops a file of the same name with .ok on the end into the receipt folder. MOTION reads it on the next run and marks that day confirmed. It is the smallest thing the other end can do, and a site that will not open a port will happily let a scheduled task write a file." },
            { kind: "note", text: "Until a receipt folder is agreed, every run stays \"sent, not confirmed\". That is the honest state — MOTION can say what it sent, but not that anything received it." },
        ],
        related: ["for-the-auditor"],
    },
];
