version: "3.8"

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: motion
    ports:
      - "5432:5432"
    volumes:
      - motion_pgdata:/var/lib/postgresql/data

volumes:
  motion_pgdata:
