import { test } from "node:test";
import assert from "node:assert/strict";
import { csvPreamble, fileName, periodPhrase, type Provenance } from "./provenance";

const base: Provenance = {
    workshop: "TipTop AutoCare",
    title: "Sales register",
    from: new Date("2026-09-01T00:00:00Z"),
    to: new Date("2026-09-30T23:59:59Z"),
    generatedAt: new Date("2026-10-02T06:15:00Z"),
    generatedBy: "Courtney Farrell",
    timezone: "Africa/Windhoek",
    rows: 42,
};

test("the period reads as a range, an as-at, or all time", () => {
    assert.equal(periodPhrase(base), "01 Sept 2026 to 30 Sept 2026");
    assert.equal(periodPhrase({ ...base, from: undefined, to: undefined, asAt: new Date("2026-09-30T00:00:00Z") }), "As at 30 Sept 2026");
    assert.equal(periodPhrase({ ...base, from: undefined, to: undefined }), "All time");
});

test("a period that ends at midnight UTC does not roll into the next day", () => {
    // 30 Sep at 23:59:59Z is 1 Oct in Windhoek. A period boundary is a calendar
    // date somebody typed, not an instant, and printing it as one gives a
    // report headed with a date that ties to nothing.
    assert.match(periodPhrase(base), /to 30 Sept 2026$/);
});

test("generated-at is written in the workshop's timezone, not UTC", () => {
    // 06:15 UTC is 08:15 in Windhoek. A file stamped two hours before the last
    // receipt on it invites a question that takes an hour to answer.
    assert.match(csvPreamble(base), /02 Oct 2026, 08:15 \(Africa\/Windhoek\)/);
});

test("the preamble carries the five facts, then a blank line", () => {
    const lines = csvPreamble(base).split("\r\n");
    assert.equal(lines[0], "MOTION Workshop Manager,");
    assert.deepEqual(lines.slice(1, 4), ["Report,Sales register", "Workshop,TipTop AutoCare", "Period,01 Sept 2026 to 30 Sept 2026"]);
    assert.equal(lines[5], "Generated by,Courtney Farrell");
    assert.equal(lines[6], "Rows,42");
    // The blank line is what an importer skips to.
    assert.equal(lines[7], "");
});

test("a workshop named with a formula cannot smuggle one into the preamble", () => {
    assert.match(csvPreamble({ ...base, workshop: "=cmd|'/c calc'!A1" }), /Workshop,'=cmd/);
});

test("the file name says what it is and when", () => {
    assert.equal(fileName(base, "pdf"), "tiptop-autocare-sales-register-2026-09-01-to-2026-09-30.pdf");
    assert.equal(
        fileName({ ...base, from: undefined, to: undefined, asAt: new Date("2026-09-30T00:00:00Z"), title: "Debtors age analysis" }, "csv"),
        "tiptop-autocare-debtors-age-analysis-as-at-2026-09-30.csv",
    );
});
