import { toCsv } from "@/lib/accounting/export";

/**
 * Where a file came from.
 *
 * An auditor's first question about any spreadsheet is who produced it and
 * when. A file that cannot answer is treated as unreliable whether or not it
 * is correct, so every export MOTION writes carries the same five facts:
 * the workshop, the period, the moment it was generated, the person who asked
 * for it, and how many rows it should contain.
 *
 * The row count is not decoration. It is the only thing that catches a file
 * that was truncated on the way out — by a browser, a mail gateway, or
 * somebody opening it in a spreadsheet with a row limit — because a short file
 * is otherwise indistinguishable from a quiet period.
 *
 * Generated-at is written in the workshop's own timezone rather than UTC. A
 * council in Windhoek reconciling a day's takings is working in the day the
 * workshop worked, and a file stamped two hours earlier than the last receipt
 * on it invites a question that takes an hour to answer.
 */

export type Provenance = {
    workshop: string;
    /** What the file is: "Sales register", "Transaction log". */
    title: string;
    from?: Date;
    to?: Date;
    asAt?: Date;
    generatedAt: Date;
    generatedBy: string;
    timezone: string;
    rows: number;
};

const stamp = (d: Date, timeZone: string) =>
    d.toLocaleString("en-GB", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit", timeZone });

/**
 * A period boundary, which is a calendar date rather than an instant.
 *
 * `from` and `to` are built from the dates somebody typed, anchored at UTC
 * midnight — `to` at 23:59:59Z. Formatting that in the workshop's timezone
 * pushes it over midnight and prints a period ending 30 September as one
 * ending 1 October, which is a figure that will not tie to anything.
 * Generated-at is a real instant and is formatted in the workshop's timezone;
 * these are not.
 */
const day = (d: Date) =>
    d.toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric", timeZone: "UTC" });

/** The period in words, for a heading or a footer. */
export function periodPhrase(p: Provenance): string {
    if (p.from && p.to) return `${day(p.from)} to ${day(p.to)}`;
    if (p.asAt) return `As at ${day(p.asAt)}`;
    return "All time";
}

/**
 * The header a CSV carries before its own columns.
 *
 * Deliberately one label-and-value pair per line rather than a second table.
 * A spreadsheet opens it as two columns that a person reads and ignores, and
 * anything importing the file skips to the blank line — which is the shape
 * every accounting package already copes with, because it is the shape bank
 * statements have used for thirty years.
 *
 * The report's notes go here too, as `Note` rows, rather than at the foot of
 * the file. They are the sentences that qualify the figures — that the profit
 * is flattered because five parts had no cost on them, that a number in the
 * period is unaccounted for — and a caveat printed after six hundred rows is
 * a caveat nobody reads. On the PDF they sit under the totals because a reader
 * gets there; in a spreadsheet the only place anyone is certain to look is the
 * top.
 */
export function csvPreamble(p: Provenance, notes: string[] = []): string {
    const lines: [string, string][] = [
        ["Report", p.title],
        ["Workshop", p.workshop],
        ["Period", periodPhrase(p)],
        ["Generated", `${stamp(p.generatedAt, p.timezone)} (${p.timezone})`],
        ["Generated by", p.generatedBy],
        ["Rows", String(p.rows)],
        ...notes.map((note): [string, string] => ["Note", note]),
    ];
    return `${toCsv(["MOTION Workshop Manager", ""], lines)}\r\n`;
}

/**
 * The same facts as one line, small, at the foot of every page of a PDF.
 *
 * The workshop and the report title are left off: they are already the two
 * largest things on the page, in the letterhead. Repeating them pushed the
 * footer onto a second line, where it shares space with the page number.
 */
export function pdfFootNote(p: Provenance): string {
    return `${periodPhrase(p)} · ${p.rows} rows · generated ${stamp(p.generatedAt, p.timezone)} by ${p.generatedBy}`;
}

/** A file name a person can find again six months later. */
export function fileName(p: Provenance, extension: "csv" | "pdf"): string {
    const slug = (text: string) => text.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
    const workshop = slug(p.workshop).slice(0, 40) || "workshop";
    const iso = (d: Date) => d.toISOString().slice(0, 10);
    const when = p.from && p.to ? `${iso(p.from)}-to-${iso(p.to)}` : p.asAt ? `as-at-${iso(p.asAt)}` : iso(p.generatedAt);
    return `${workshop}-${slug(p.title)}-${when}.${extension}`;
}
